apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  DB_PASSWORD: QVZOU19Ia21hYXRYSkwxUWZINUg2MEhtblo=
  AWS_ACCESS_KEY_ID: QUtJQVpJMkxFMlowQ0xEU0dRWjd
  AWS_SECRET_ACCESS_KEY: ajRsZldKanBuTHdNTGRCUUo0WWlRWjM1RUdNbm9NeFEvWEdXNmRJ
