apiVersion: batch/v1
kind: CronJob
metadata:
  name: confidence
spec:
  schedule: "* * * * *"  # Run the job every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: confidence
            image: s6confidence/postgres-backup:v1.1.0   # Replace with your Docker image name and tag
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
               name: postgres-config
            - secretRef:
               name: aws-secret
            # volumeMounts:
            # - name: backup-volume
            #   mountPath: /backup
          restartPolicy: OnFailure
          # volumes:
          # - name: backup-volume
          #   persistentVolumeClaim:
          #     claimName: your-pvc-name  # Replace with your PersistentVolumeClaim name
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1     

