apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-restore
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-restore
            image: s6confidence/backup-restore:v1
            envFrom:
            - configMapRef:
                name: my-restore
            - secretRef:
                name: aws-secret
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3