apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: s6confidence/backup-master:v1.0.1  # Use an image with MySQL client tools installed
            envFrom:
            configMapRef
              - name: postgres-config
            secretKeyRef:
              -  name: aws-secret
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            emptyDir: {}
          restartPolicy: OnFailure
