apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImN6WmpiMjVtYVdSbGJtTmxPbVJsYzJsTllXZG5hV1UyTlVCQmRtVnRaUT09IgoJCX0KCX0KfQ=="